### ISSUE TITLE
Home page constantly loops on fresh deployment

### ISSUE THREAD

**Issue by TheoBr** [Likeminded/Likeminded#2]
No idea what is causing this at the moment, seems to be redirecting to the route /b and back to the index route over and over again

**Comment by TheoBr** [comment]
Found the error that causes the bounce back, message below

```
ActionController::RoutingError (No route matches [GET] "/beliefs/beliefs.list.html"):
  actionpack (3.2.22.2) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  rollbar (2.8.3) lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
  actionpack (3.2.22.2) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.22.2) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.22.2) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.22.2) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.22.2) lib/rails/rack/logger.rb:16:in `call'
  quiet_assets (1.0.1) lib/quiet_assets.rb:20:in `call_with_quiet_assets'
  actionpack (3.2.22.2) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.7) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.7) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.22.2) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.7) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.22.2) lib/action_dispatch/middleware/static.rb:83:in `call'
  railties (3.2.22.2) lib/rails/engine.rb:484:in `call'
  railties (3.2.22.2) lib/rails/application.rb:231:in `call'
  rack (1.4.7) lib/rack/content_length.rb:14:in `call'
  railties (3.2.22.2) lib/rails/rack/log_tailer.rb:17:in `call'
  rack (1.4.7) lib/rack/handler/webrick.rb:59:in `service'
  /Users/theo/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /Users/theo/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /Users/theo/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

**Comment by TheoBr** [comment]
Solved when there are users in the users.db
